apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: debug-server
          image: k3d-netzregistry.localhost:3001/debug-server:latest
          ports:
            - name: http-port
              containerPort: 5000
        - name: api-local-proxy
          image: k3d-netzregistry.localhost:3001/api-local-proxy:latest
          ports:
            - name: envoy-port
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app.kubernetes.io/name: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: envoy-port
