apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: debug-server
          image: k3d-netzregistry.localhost:3001/debug-server:latest
          ports:
            - name: http-port
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app.kubernetes.io/name: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-svc
                port:
                  number: 80
