FROM --platform=linux/amd64 k3d-netzregistry.localhost:3001/base AS builder

COPY envoy.config.json envoy.config.json

RUN mkdir logs && \
    ./envoy --mode validate --config-path ./envoy.config.json

# ------

FROM --platform=linux/amd64 k3d-netzregistry.localhost:3001/base

ENV NETZ_SERVICE={{.Name}}

RUN mkdir logs

COPY --from=builder /home/main/envoy.config.json envoy.config.json

ENTRYPOINT ["./envoy"]

CMD ["--config-path", "envoy.config.json"]
